### ISSUE TITLE
Sorting question in Node JS

### ISSUE THREAD

**Issue by RAImmers** [griddb/griddb_nosql#145]
Hi,
My list is correct sorted by Name. I also use a field called Inactive and has the values 0 and 1.
I like to have the sorted: not Inactive and then by name. Can anyone help me with the correct sorting of my list?

My code:
params.list = sorted.sort((i1, i2) => {
     if (i1.Name.toLowerCase() < i2.Name.toLowerCase()) return -1;
     if (i1.Name.toLowerCase() === i2.Name.toLowerCase()) return 0;
     if (i1.Name.toLowerCase() > i2.Name.toLowerCase()) return 1;
    });

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
So, I'll colse it.

And I guess there are useful information for you in stackoverflow.
https://stackoverflow.com/questions/6129952/javascript-sort-array-by-two-fields
Javascript sort array by two fields
https://stackoverflow.com/questions/39302871/filter-and-sort-a-javascript-array
Filter and sort a JavaScript array
